# Generated by Django 4.2.7 on 2024-03-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friendMessage_to_user',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friend_id', models.IntegerField(primary_key=True, serialize=False)),
                ('friend_name', models.CharField(max_length=30)),
                ('friendmessage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.friendmessage_to_user')),
            ],
        ),
        migrations.CreateModel(
            name='Group_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('group_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group_users')),
            ],
        ),
        migrations.CreateModel(
            name='othersMessage_to_group',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage_to_friends',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage_to_group',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.friends')),
                ('groupchat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.groupchat')),
            ],
        ),
        migrations.AddField(
            model_name='group_users',
            name='othersmessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.othersmessage_to_group'),
        ),
        migrations.AddField(
            model_name='group_users',
            name='usermessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usermessage_to_group'),
        ),
        migrations.AddField(
            model_name='friends',
            name='usermessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usermessage_to_friends'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
