# Generated by Django 4.2.7 on 2024-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendmessage',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='usermessage',
        ),
        migrations.AddField(
            model_name='friends',
            name='friendmessage',
            field=models.ManyToManyField(blank=True, null=True, to='app.friendmessage_to_user'),
        ),
        migrations.AddField(
            model_name='friends',
            name='usermessage',
            field=models.ManyToManyField(blank=True, null=True, to='app.usermessage_to_friends'),
        ),
    ]
