# Generated by Django 4.2.4 on 2024-03-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_comment_user_id_alter_post_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.users"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.users"
            ),
        ),
    ]
