# Generated by Django 4.2.4 on 2024-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_comment_actual_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="friends",),
        migrations.AddField(
            model_name="users",
            name="friends",
            field=models.ManyToManyField(blank=True, null=True, to="app.friends"),
        ),
    ]
