# Generated by Django 4.2.4 on 2024-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_user_friends_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_friends",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
