# Generated by Django 4.2.4 on 2024-03-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_user_friends_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user_friends", unique_together={("user_id", "friend_id")},
        ),
    ]
