# Generated by Django 4.2.4 on 2024-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_user_friends_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
